---
- hosts: localhost
  connection: local
  tasks:
  - name: create target group
    elb_target_group:
      name: ecsTargetGroup
      protocol: http
      port: 80
      vpc_id: vpc-7d370a1a
      region: ap-southeast-1
      state: present
    register: elb_target_group_out
  - debug: var=elb_target_group_out["target_group_arn"]
  - name: Create SG for ELB
    ec2_group:
      name: ECS-ELB-sg
      vpc_id: vpc-7d370a1a
      description: 'node sg for ECS-ELB-sg'
      region: ap-southeast-1
      rules:
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 80
    register: sg_group
  - name: Create ALB for ecs service
    elb_application_lb:
      name: ecsELB
      security_groups:
        - '{{sg_group["group_id"]}}'
      subnets:
        - subnet-2f1cfa49
        - subnet-5e3c2a17
        - subnet-ac1ac7f5
      listeners:
        - Protocol: HTTP
          Port: 80
          DefaultActions:
            - Type: forward
              TargetGroupName: '{{elb_target_group_out["target_group_name"]}}'
      region: ap-southeast-1
      state: present
    register: elb_application_lb_out
  - debug: var=elb_application_lb_out

