---
- hosts: target5
  gather_facts: true
  become: true
  vars_files:
    - "vars/main.yml"
  tasks:
#  - name: upgrade OS
#    apt:
#      name: "*"
#      state: latest
  - name: Install dependencies
    apt: 
      name: ['python', 'python-setuptools', 'python-dev', 'python-pip', 'build-essential']
      state: latest
  - include: tasks/deploy_db.yml
  - include: tasks/deploy_web.yml
