---
- hosts: localhost
  connection: local
  tasks:
  - name: Define task defifnition
    ecs_taskdefinition:
      family: httpdTaskDef
      containers:
        - name: httpdcontainer
          cpu: 1
          image: "httpd:2.4"
          memory: 128
          portMappings:
          - containerPort: 80
            hostPort: 0
          logConfiguration:
            logDriver: awslogs
            options:
              awslogs-group: /ecs/httpd
              awslogs-region: ap-southeast-1
      state: present
      region: ap-southeast-1
